// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/emergencia/emergencia.proto

package emergencia

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Emergencia struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      int32                  `protobuf:"varint,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     int32                  `protobuf:"varint,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Magnitude     int32                  `protobuf:"varint,4,opt,name=magnitude,proto3" json:"magnitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Emergencia) Reset() {
	*x = Emergencia{}
	mi := &file_proto_emergencia_emergencia_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Emergencia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emergencia) ProtoMessage() {}

func (x *Emergencia) ProtoReflect() protoreflect.Message {
	mi := &file_proto_emergencia_emergencia_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Emergencia.ProtoReflect.Descriptor instead.
func (*Emergencia) Descriptor() ([]byte, []int) {
	return file_proto_emergencia_emergencia_proto_rawDescGZIP(), []int{0}
}

func (x *Emergencia) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Emergencia) GetLatitude() int32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Emergencia) GetLongitude() int32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Emergencia) GetMagnitude() int32 {
	if x != nil {
		return x.Magnitude
	}
	return 0
}

type Emergencias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lista         []*Emergencia          `protobuf:"bytes,1,rep,name=lista,proto3" json:"lista,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Emergencias) Reset() {
	*x = Emergencias{}
	mi := &file_proto_emergencia_emergencia_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Emergencias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emergencias) ProtoMessage() {}

func (x *Emergencias) ProtoReflect() protoreflect.Message {
	mi := &file_proto_emergencia_emergencia_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Emergencias.ProtoReflect.Descriptor instead.
func (*Emergencias) Descriptor() ([]byte, []int) {
	return file_proto_emergencia_emergencia_proto_rawDescGZIP(), []int{1}
}

func (x *Emergencias) GetLista() []*Emergencia {
	if x != nil {
		return x.Lista
	}
	return nil
}

type Estado struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Estado) Reset() {
	*x = Estado{}
	mi := &file_proto_emergencia_emergencia_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Estado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Estado) ProtoMessage() {}

func (x *Estado) ProtoReflect() protoreflect.Message {
	mi := &file_proto_emergencia_emergencia_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Estado.ProtoReflect.Descriptor instead.
func (*Estado) Descriptor() ([]byte, []int) {
	return file_proto_emergencia_emergencia_proto_rawDescGZIP(), []int{2}
}

func (x *Estado) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

var File_proto_emergencia_emergencia_proto protoreflect.FileDescriptor

const file_proto_emergencia_emergencia_proto_rawDesc = "" +
	"\n" +
	"!proto/emergencia/emergencia.proto\x12\n" +
	"emergencia\"x\n" +
	"\n" +
	"Emergencia\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x05R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x05R\tlongitude\x12\x1c\n" +
	"\tmagnitude\x18\x04 \x01(\x05R\tmagnitude\";\n" +
	"\vEmergencias\x12,\n" +
	"\x05lista\x18\x01 \x03(\v2\x16.emergencia.EmergenciaR\x05lista\"\"\n" +
	"\x06Estado\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje2U\n" +
	"\x11AsignacionService\x12@\n" +
	"\x11EnviarEmergencias\x12\x17.emergencia.Emergencias\x1a\x12.emergencia.EstadoB\x14Z\x12./proto;emergenciab\x06proto3"

var (
	file_proto_emergencia_emergencia_proto_rawDescOnce sync.Once
	file_proto_emergencia_emergencia_proto_rawDescData []byte
)

func file_proto_emergencia_emergencia_proto_rawDescGZIP() []byte {
	file_proto_emergencia_emergencia_proto_rawDescOnce.Do(func() {
		file_proto_emergencia_emergencia_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_emergencia_emergencia_proto_rawDesc), len(file_proto_emergencia_emergencia_proto_rawDesc)))
	})
	return file_proto_emergencia_emergencia_proto_rawDescData
}

var file_proto_emergencia_emergencia_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_emergencia_emergencia_proto_goTypes = []any{
	(*Emergencia)(nil),  // 0: emergencia.Emergencia
	(*Emergencias)(nil), // 1: emergencia.Emergencias
	(*Estado)(nil),      // 2: emergencia.Estado
}
var file_proto_emergencia_emergencia_proto_depIdxs = []int32{
	0, // 0: emergencia.Emergencias.lista:type_name -> emergencia.Emergencia
	1, // 1: emergencia.AsignacionService.EnviarEmergencias:input_type -> emergencia.Emergencias
	2, // 2: emergencia.AsignacionService.EnviarEmergencias:output_type -> emergencia.Estado
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_emergencia_emergencia_proto_init() }
func file_proto_emergencia_emergencia_proto_init() {
	if File_proto_emergencia_emergencia_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_emergencia_emergencia_proto_rawDesc), len(file_proto_emergencia_emergencia_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_emergencia_emergencia_proto_goTypes,
		DependencyIndexes: file_proto_emergencia_emergencia_proto_depIdxs,
		MessageInfos:      file_proto_emergencia_emergencia_proto_msgTypes,
	}.Build()
	File_proto_emergencia_emergencia_proto = out.File
	file_proto_emergencia_emergencia_proto_goTypes = nil
	file_proto_emergencia_emergencia_proto_depIdxs = nil
}
