// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: proto/emergencia/emergencia.proto

package emergencia

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AsignacionService_EnviarEmergencias_FullMethodName = "/emergencia.AsignacionService/EnviarEmergencias"
)

// AsignacionServiceClient is the client API for AsignacionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AsignacionServiceClient interface {
	EnviarEmergencias(ctx context.Context, in *Emergencias, opts ...grpc.CallOption) (*Estado, error)
}

type asignacionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAsignacionServiceClient(cc grpc.ClientConnInterface) AsignacionServiceClient {
	return &asignacionServiceClient{cc}
}

func (c *asignacionServiceClient) EnviarEmergencias(ctx context.Context, in *Emergencias, opts ...grpc.CallOption) (*Estado, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Estado)
	err := c.cc.Invoke(ctx, AsignacionService_EnviarEmergencias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AsignacionServiceServer is the server API for AsignacionService service.
// All implementations must embed UnimplementedAsignacionServiceServer
// for forward compatibility.
type AsignacionServiceServer interface {
	EnviarEmergencias(context.Context, *Emergencias) (*Estado, error)
	mustEmbedUnimplementedAsignacionServiceServer()
}

// UnimplementedAsignacionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAsignacionServiceServer struct{}

func (UnimplementedAsignacionServiceServer) EnviarEmergencias(context.Context, *Emergencias) (*Estado, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnviarEmergencias not implemented")
}
func (UnimplementedAsignacionServiceServer) mustEmbedUnimplementedAsignacionServiceServer() {}
func (UnimplementedAsignacionServiceServer) testEmbeddedByValue()                           {}

// UnsafeAsignacionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AsignacionServiceServer will
// result in compilation errors.
type UnsafeAsignacionServiceServer interface {
	mustEmbedUnimplementedAsignacionServiceServer()
}

func RegisterAsignacionServiceServer(s grpc.ServiceRegistrar, srv AsignacionServiceServer) {
	// If the following call pancis, it indicates UnimplementedAsignacionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AsignacionService_ServiceDesc, srv)
}

func _AsignacionService_EnviarEmergencias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Emergencias)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsignacionServiceServer).EnviarEmergencias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsignacionService_EnviarEmergencias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsignacionServiceServer).EnviarEmergencias(ctx, req.(*Emergencias))
	}
	return interceptor(ctx, in, info, handler)
}

// AsignacionService_ServiceDesc is the grpc.ServiceDesc for AsignacionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AsignacionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emergencia.AsignacionService",
	HandlerType: (*AsignacionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnviarEmergencias",
			Handler:    _AsignacionService_EnviarEmergencias_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/emergencia/emergencia.proto",
}
