// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: proto/monitoreo/monitoreo.proto

package monitoreo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServicioMonitoreo_RecibirActualizaciones_FullMethodName = "/monitoreo.ServicioMonitoreo/RecibirActualizaciones"
)

// ServicioMonitoreoClient is the client API for ServicioMonitoreo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServicioMonitoreoClient interface {
	RecibirActualizaciones(ctx context.Context, in *Actualizacion, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Actualizacion], error)
}

type servicioMonitoreoClient struct {
	cc grpc.ClientConnInterface
}

func NewServicioMonitoreoClient(cc grpc.ClientConnInterface) ServicioMonitoreoClient {
	return &servicioMonitoreoClient{cc}
}

func (c *servicioMonitoreoClient) RecibirActualizaciones(ctx context.Context, in *Actualizacion, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Actualizacion], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ServicioMonitoreo_ServiceDesc.Streams[0], ServicioMonitoreo_RecibirActualizaciones_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Actualizacion, Actualizacion]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServicioMonitoreo_RecibirActualizacionesClient = grpc.ServerStreamingClient[Actualizacion]

// ServicioMonitoreoServer is the server API for ServicioMonitoreo service.
// All implementations must embed UnimplementedServicioMonitoreoServer
// for forward compatibility.
type ServicioMonitoreoServer interface {
	RecibirActualizaciones(*Actualizacion, grpc.ServerStreamingServer[Actualizacion]) error
	mustEmbedUnimplementedServicioMonitoreoServer()
}

// UnimplementedServicioMonitoreoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServicioMonitoreoServer struct{}

func (UnimplementedServicioMonitoreoServer) RecibirActualizaciones(*Actualizacion, grpc.ServerStreamingServer[Actualizacion]) error {
	return status.Errorf(codes.Unimplemented, "method RecibirActualizaciones not implemented")
}
func (UnimplementedServicioMonitoreoServer) mustEmbedUnimplementedServicioMonitoreoServer() {}
func (UnimplementedServicioMonitoreoServer) testEmbeddedByValue()                           {}

// UnsafeServicioMonitoreoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServicioMonitoreoServer will
// result in compilation errors.
type UnsafeServicioMonitoreoServer interface {
	mustEmbedUnimplementedServicioMonitoreoServer()
}

func RegisterServicioMonitoreoServer(s grpc.ServiceRegistrar, srv ServicioMonitoreoServer) {
	// If the following call pancis, it indicates UnimplementedServicioMonitoreoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServicioMonitoreo_ServiceDesc, srv)
}

func _ServicioMonitoreo_RecibirActualizaciones_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Actualizacion)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServicioMonitoreoServer).RecibirActualizaciones(m, &grpc.GenericServerStream[Actualizacion, Actualizacion]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServicioMonitoreo_RecibirActualizacionesServer = grpc.ServerStreamingServer[Actualizacion]

// ServicioMonitoreo_ServiceDesc is the grpc.ServiceDesc for ServicioMonitoreo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServicioMonitoreo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitoreo.ServicioMonitoreo",
	HandlerType: (*ServicioMonitoreoServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RecibirActualizaciones",
			Handler:       _ServicioMonitoreo_RecibirActualizaciones_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/monitoreo/monitoreo.proto",
}
