// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: proto/cliente.proto

package emergencia

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Asignacion_EnviarEmergencias_FullMethodName = "/emergencia.Asignacion/EnviarEmergencias"
)

// AsignacionClient is the client API for Asignacion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AsignacionClient interface {
	EnviarEmergencias(ctx context.Context, in *EmergenciaList, opts ...grpc.CallOption) (*Respuesta, error)
}

type asignacionClient struct {
	cc grpc.ClientConnInterface
}

func NewAsignacionClient(cc grpc.ClientConnInterface) AsignacionClient {
	return &asignacionClient{cc}
}

func (c *asignacionClient) EnviarEmergencias(ctx context.Context, in *EmergenciaList, opts ...grpc.CallOption) (*Respuesta, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Respuesta)
	err := c.cc.Invoke(ctx, Asignacion_EnviarEmergencias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AsignacionServer is the server API for Asignacion service.
// All implementations must embed UnimplementedAsignacionServer
// for forward compatibility.
type AsignacionServer interface {
	EnviarEmergencias(context.Context, *EmergenciaList) (*Respuesta, error)
	mustEmbedUnimplementedAsignacionServer()
}

// UnimplementedAsignacionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAsignacionServer struct{}

func (UnimplementedAsignacionServer) EnviarEmergencias(context.Context, *EmergenciaList) (*Respuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnviarEmergencias not implemented")
}
func (UnimplementedAsignacionServer) mustEmbedUnimplementedAsignacionServer() {}
func (UnimplementedAsignacionServer) testEmbeddedByValue()                    {}

// UnsafeAsignacionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AsignacionServer will
// result in compilation errors.
type UnsafeAsignacionServer interface {
	mustEmbedUnimplementedAsignacionServer()
}

func RegisterAsignacionServer(s grpc.ServiceRegistrar, srv AsignacionServer) {
	// If the following call pancis, it indicates UnimplementedAsignacionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Asignacion_ServiceDesc, srv)
}

func _Asignacion_EnviarEmergencias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmergenciaList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsignacionServer).EnviarEmergencias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Asignacion_EnviarEmergencias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsignacionServer).EnviarEmergencias(ctx, req.(*EmergenciaList))
	}
	return interceptor(ctx, in, info, handler)
}

// Asignacion_ServiceDesc is the grpc.ServiceDesc for Asignacion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Asignacion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emergencia.Asignacion",
	HandlerType: (*AsignacionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnviarEmergencias",
			Handler:    _Asignacion_EnviarEmergencias_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cliente.proto",
}
