// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/dronesasignacion/dronesasignacion.proto

package dronesasignacion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AsignacionEmergencia struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DroneId       string                 `protobuf:"bytes,1,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Latitude      int32                  `protobuf:"varint,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     int32                  `protobuf:"varint,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Magnitud      int32                  `protobuf:"varint,5,opt,name=magnitud,proto3" json:"magnitud,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsignacionEmergencia) Reset() {
	*x = AsignacionEmergencia{}
	mi := &file_proto_dronesasignacion_dronesasignacion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsignacionEmergencia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsignacionEmergencia) ProtoMessage() {}

func (x *AsignacionEmergencia) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dronesasignacion_dronesasignacion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsignacionEmergencia.ProtoReflect.Descriptor instead.
func (*AsignacionEmergencia) Descriptor() ([]byte, []int) {
	return file_proto_dronesasignacion_dronesasignacion_proto_rawDescGZIP(), []int{0}
}

func (x *AsignacionEmergencia) GetDroneId() string {
	if x != nil {
		return x.DroneId
	}
	return ""
}

func (x *AsignacionEmergencia) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *AsignacionEmergencia) GetLatitude() int32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *AsignacionEmergencia) GetLongitude() int32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *AsignacionEmergencia) GetMagnitud() int32 {
	if x != nil {
		return x.Magnitud
	}
	return 0
}

type ResultadoEmergencia struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DroneId       string                 `protobuf:"bytes,1,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Resultado     string                 `protobuf:"bytes,3,opt,name=resultado,proto3" json:"resultado,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultadoEmergencia) Reset() {
	*x = ResultadoEmergencia{}
	mi := &file_proto_dronesasignacion_dronesasignacion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultadoEmergencia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoEmergencia) ProtoMessage() {}

func (x *ResultadoEmergencia) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dronesasignacion_dronesasignacion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoEmergencia.ProtoReflect.Descriptor instead.
func (*ResultadoEmergencia) Descriptor() ([]byte, []int) {
	return file_proto_dronesasignacion_dronesasignacion_proto_rawDescGZIP(), []int{1}
}

func (x *ResultadoEmergencia) GetDroneId() string {
	if x != nil {
		return x.DroneId
	}
	return ""
}

func (x *ResultadoEmergencia) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *ResultadoEmergencia) GetResultado() string {
	if x != nil {
		return x.Resultado
	}
	return ""
}

type Respuesta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Respuesta) Reset() {
	*x = Respuesta{}
	mi := &file_proto_dronesasignacion_dronesasignacion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Respuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respuesta) ProtoMessage() {}

func (x *Respuesta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dronesasignacion_dronesasignacion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respuesta.ProtoReflect.Descriptor instead.
func (*Respuesta) Descriptor() ([]byte, []int) {
	return file_proto_dronesasignacion_dronesasignacion_proto_rawDescGZIP(), []int{2}
}

func (x *Respuesta) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

var File_proto_dronesasignacion_dronesasignacion_proto protoreflect.FileDescriptor

const file_proto_dronesasignacion_dronesasignacion_proto_rawDesc = "" +
	"\n" +
	"-proto/dronesasignacion/dronesasignacion.proto\x12\x10dronesasignacion\"\x9f\x01\n" +
	"\x14AsignacionEmergencia\x12\x19\n" +
	"\bdrone_id\x18\x01 \x01(\tR\adroneId\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x05R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x05R\tlongitude\x12\x1a\n" +
	"\bmagnitud\x18\x05 \x01(\x05R\bmagnitud\"f\n" +
	"\x13ResultadoEmergencia\x12\x19\n" +
	"\bdrone_id\x18\x01 \x01(\tR\adroneId\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x1c\n" +
	"\tresultado\x18\x03 \x01(\tR\tresultado\"%\n" +
	"\tRespuesta\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje2g\n" +
	"\vDronService\x12X\n" +
	"\x11RecibirAsignacion\x12&.dronesasignacion.AsignacionEmergencia\x1a\x1b.dronesasignacion.Respuesta2m\n" +
	"\x11AsignacionService\x12X\n" +
	"\x12NotificarResultado\x12%.dronesasignacion.ResultadoEmergencia\x1a\x1b.dronesasignacion.RespuestaB\"Z SD-Tarea2/proto;dronesasignacionb\x06proto3"

var (
	file_proto_dronesasignacion_dronesasignacion_proto_rawDescOnce sync.Once
	file_proto_dronesasignacion_dronesasignacion_proto_rawDescData []byte
)

func file_proto_dronesasignacion_dronesasignacion_proto_rawDescGZIP() []byte {
	file_proto_dronesasignacion_dronesasignacion_proto_rawDescOnce.Do(func() {
		file_proto_dronesasignacion_dronesasignacion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dronesasignacion_dronesasignacion_proto_rawDesc), len(file_proto_dronesasignacion_dronesasignacion_proto_rawDesc)))
	})
	return file_proto_dronesasignacion_dronesasignacion_proto_rawDescData
}

var file_proto_dronesasignacion_dronesasignacion_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_dronesasignacion_dronesasignacion_proto_goTypes = []any{
	(*AsignacionEmergencia)(nil), // 0: dronesasignacion.AsignacionEmergencia
	(*ResultadoEmergencia)(nil),  // 1: dronesasignacion.ResultadoEmergencia
	(*Respuesta)(nil),            // 2: dronesasignacion.Respuesta
}
var file_proto_dronesasignacion_dronesasignacion_proto_depIdxs = []int32{
	0, // 0: dronesasignacion.DronService.RecibirAsignacion:input_type -> dronesasignacion.AsignacionEmergencia
	1, // 1: dronesasignacion.AsignacionService.NotificarResultado:input_type -> dronesasignacion.ResultadoEmergencia
	2, // 2: dronesasignacion.DronService.RecibirAsignacion:output_type -> dronesasignacion.Respuesta
	2, // 3: dronesasignacion.AsignacionService.NotificarResultado:output_type -> dronesasignacion.Respuesta
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_dronesasignacion_dronesasignacion_proto_init() }
func file_proto_dronesasignacion_dronesasignacion_proto_init() {
	if File_proto_dronesasignacion_dronesasignacion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dronesasignacion_dronesasignacion_proto_rawDesc), len(file_proto_dronesasignacion_dronesasignacion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_dronesasignacion_dronesasignacion_proto_goTypes,
		DependencyIndexes: file_proto_dronesasignacion_dronesasignacion_proto_depIdxs,
		MessageInfos:      file_proto_dronesasignacion_dronesasignacion_proto_msgTypes,
	}.Build()
	File_proto_dronesasignacion_dronesasignacion_proto = out.File
	file_proto_dronesasignacion_dronesasignacion_proto_goTypes = nil
	file_proto_dronesasignacion_dronesasignacion_proto_depIdxs = nil
}
