// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: proto/dronesasignacion/dronesasignacion.proto

package dronesasignacion

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DronService_RecibirAsignacion_FullMethodName = "/dronesasignacion.DronService/RecibirAsignacion"
)

// DronServiceClient is the client API for DronService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio que implementa Drones (servidor)
type DronServiceClient interface {
	RecibirAsignacion(ctx context.Context, in *AsignacionEmergencia, opts ...grpc.CallOption) (*Respuesta, error)
}

type dronServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDronServiceClient(cc grpc.ClientConnInterface) DronServiceClient {
	return &dronServiceClient{cc}
}

func (c *dronServiceClient) RecibirAsignacion(ctx context.Context, in *AsignacionEmergencia, opts ...grpc.CallOption) (*Respuesta, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Respuesta)
	err := c.cc.Invoke(ctx, DronService_RecibirAsignacion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DronServiceServer is the server API for DronService service.
// All implementations must embed UnimplementedDronServiceServer
// for forward compatibility.
//
// Servicio que implementa Drones (servidor)
type DronServiceServer interface {
	RecibirAsignacion(context.Context, *AsignacionEmergencia) (*Respuesta, error)
	mustEmbedUnimplementedDronServiceServer()
}

// UnimplementedDronServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDronServiceServer struct{}

func (UnimplementedDronServiceServer) RecibirAsignacion(context.Context, *AsignacionEmergencia) (*Respuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecibirAsignacion not implemented")
}
func (UnimplementedDronServiceServer) mustEmbedUnimplementedDronServiceServer() {}
func (UnimplementedDronServiceServer) testEmbeddedByValue()                     {}

// UnsafeDronServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DronServiceServer will
// result in compilation errors.
type UnsafeDronServiceServer interface {
	mustEmbedUnimplementedDronServiceServer()
}

func RegisterDronServiceServer(s grpc.ServiceRegistrar, srv DronServiceServer) {
	// If the following call pancis, it indicates UnimplementedDronServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DronService_ServiceDesc, srv)
}

func _DronService_RecibirAsignacion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AsignacionEmergencia)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DronServiceServer).RecibirAsignacion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DronService_RecibirAsignacion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DronServiceServer).RecibirAsignacion(ctx, req.(*AsignacionEmergencia))
	}
	return interceptor(ctx, in, info, handler)
}

// DronService_ServiceDesc is the grpc.ServiceDesc for DronService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DronService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dronesasignacion.DronService",
	HandlerType: (*DronServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecibirAsignacion",
			Handler:    _DronService_RecibirAsignacion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dronesasignacion/dronesasignacion.proto",
}

const (
	AsignacionService_NotificarResultado_FullMethodName = "/dronesasignacion.AsignacionService/NotificarResultado"
)

// AsignacionServiceClient is the client API for AsignacionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio que implementa Asignacion (servidor)
type AsignacionServiceClient interface {
	NotificarResultado(ctx context.Context, in *ResultadoEmergencia, opts ...grpc.CallOption) (*Respuesta, error)
}

type asignacionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAsignacionServiceClient(cc grpc.ClientConnInterface) AsignacionServiceClient {
	return &asignacionServiceClient{cc}
}

func (c *asignacionServiceClient) NotificarResultado(ctx context.Context, in *ResultadoEmergencia, opts ...grpc.CallOption) (*Respuesta, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Respuesta)
	err := c.cc.Invoke(ctx, AsignacionService_NotificarResultado_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AsignacionServiceServer is the server API for AsignacionService service.
// All implementations must embed UnimplementedAsignacionServiceServer
// for forward compatibility.
//
// Servicio que implementa Asignacion (servidor)
type AsignacionServiceServer interface {
	NotificarResultado(context.Context, *ResultadoEmergencia) (*Respuesta, error)
	mustEmbedUnimplementedAsignacionServiceServer()
}

// UnimplementedAsignacionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAsignacionServiceServer struct{}

func (UnimplementedAsignacionServiceServer) NotificarResultado(context.Context, *ResultadoEmergencia) (*Respuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotificarResultado not implemented")
}
func (UnimplementedAsignacionServiceServer) mustEmbedUnimplementedAsignacionServiceServer() {}
func (UnimplementedAsignacionServiceServer) testEmbeddedByValue()                           {}

// UnsafeAsignacionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AsignacionServiceServer will
// result in compilation errors.
type UnsafeAsignacionServiceServer interface {
	mustEmbedUnimplementedAsignacionServiceServer()
}

func RegisterAsignacionServiceServer(s grpc.ServiceRegistrar, srv AsignacionServiceServer) {
	// If the following call pancis, it indicates UnimplementedAsignacionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AsignacionService_ServiceDesc, srv)
}

func _AsignacionService_NotificarResultado_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResultadoEmergencia)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsignacionServiceServer).NotificarResultado(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsignacionService_NotificarResultado_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsignacionServiceServer).NotificarResultado(ctx, req.(*ResultadoEmergencia))
	}
	return interceptor(ctx, in, info, handler)
}

// AsignacionService_ServiceDesc is the grpc.ServiceDesc for AsignacionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AsignacionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dronesasignacion.AsignacionService",
	HandlerType: (*AsignacionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotificarResultado",
			Handler:    _AsignacionService_NotificarResultado_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dronesasignacion/dronesasignacion.proto",
}
